service: eventbridge-poc
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  eventBridge:
    useCloudFormation: true
  logs:
    restApi: true
  tracing:
    apiGateway: true
    lambda: true
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - xray:PutTelemetryRecords
        - xray:PutTraceSegments
      Resource: "*"
  environment:
    SUBMISSIONS_BUCKET: ${env:SUBMISSIONS_BUCKET}
    SUBMISSIONS_DMZ_BUCKET: ${env:SUBMISSIONS_DMZ_BUCKET}
    SUBMISSIONS_QUARANTINE_BUCKET: ${env:SUBMISSIONS_QUARANTINE_BUCKET}
    CHALLENGES_TABLE: ${env:CHALLENGES_TABLE}
    SUBMISSIONS_TABLE: ${env:SUBMISSIONS_TABLE}
    SUBMISSION_REVIEWS_TABLE: ${env:SUBMISSION_REVIEWS_TABLE}

package:
  individually: true

plugins:
  - serverless-iam-roles-per-function
  - serverless-dynamodb-to-eventbridge-plugin
  - serverless-bundle

resources:
  # Only create CloudTrail resources if necessary
  Conditions:
    CreateCloudTrail:
      Fn::Equals:
        - ${env:CREATE_CLOUDTRAIL, false}
        - true
  Resources:
    # S3 buckets
    SubmissionsDmzBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:SUBMISSIONS_DMZ_BUCKET}
    SubmissionsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:SUBMISSIONS_BUCKET}
    SubmissionsQuarantineBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:SUBMISSIONS_QUARANTINE_BUCKET}

    # DynamoDB tables
    ChallengesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:CHALLENGES_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: status
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: StatusIndex
            KeySchema:
              - AttributeName: status
                KeyType: HASH
            Projection:
              NonKeyAttributes:
                - id
                - name
                - numberOfSubmissions
              ProjectionType: INCLUDE
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
    SubmissionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:SUBMISSIONS_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: filename
            AttributeType: S
          - AttributeName: challengeId
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: FilenameIndex
            KeySchema:
              - AttributeName: filename
                KeyType: HASH
            Projection:
              NonKeyAttributes:
                - id
              ProjectionType: INCLUDE
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: ChallengeIndex
            KeySchema:
              - AttributeName: challengeId
                KeyType: HASH
            Projection:
              NonKeyAttributes:
                - id
              ProjectionType: INCLUDE
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    ReviewsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:SUBMISSION_REVIEWS_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: submissionId
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: SubmissionIndex
            KeySchema:
              - AttributeName: submissionId
                KeyType: HASH
            Projection:
              NonKeyAttributes:
                - id
              ProjectionType: INCLUDE
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

functions:
  # API Gateway handler functions
  createChallenge:
    handler: handlers/api/create-challenge.handler
    events:
      - http:
          path: /eventbridge-poc-challenges
          method: post
          request:
            schemas:
              application/json: ${file(./schema/create-challenge.json)}
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: !GetAtt ChallengesTable.Arn

  listChallenges:
    handler: handlers/api/list-challenges.handler
    events:
      - http:
          path: /eventbridge-poc-challenges
          method: get
          request:
            parameters:
              querystrings:
                status: false
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Scan
        Resource: !GetAtt ChallengesTable.Arn
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: !Sub ${ChallengesTable.Arn}/index/StatusIndex
  listSubmissions:
    handler: handlers/api/list-submissions.handler
    events:
      - http:
          path: /eventbridge-poc-challenges/{challengeId}/submissions
          method: get
          request:
            parameters:
              paths:
                challengeId: true
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Scan
        Resource: !GetAtt SubmissionsTable.Arn
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: !Sub ${SubmissionsTable.Arn}/index/ChallengeIndex

  createReview:
    handler: handlers/api/create-review.handler
    events:
      - http:
          path: /eventbridge-poc-submissions/{submissionId}/reviews
          method: post
          request:
            parameters:
              paths:
                submissionId: true
            schemas:
              application/json: ${file(./schema/create-review.json)}
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: !GetAtt ReviewsTable.Arn
      - Effect: Allow
        Action:
          - dynamodb:GetItem
        Resource: !GetAtt SubmissionsTable.Arn
      - Effect: Allow
        Action:
          - dynamodb:GetItem
        Resource: !GetAtt ChallengesTable.Arn

  # EventBridge handler functions
  processSubmission:
    handler: handlers/events/process-submission.handler
    events:
      - eventBridge:
          pattern:
            source:
              - aws.s3
            detail-type:
              - AWS API Call via CloudTrail
            detail:
              eventSource:
                - s3.amazonaws.com
              eventName:
                - PutObject
              requestParameters:
                bucketName:
                  - ${env:SUBMISSIONS_DMZ_BUCKET}
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: !GetAtt SubmissionsTable.Arn
      - Effect: Allow
        Action:
          - dynamodb:GetItem
        Resource: !GetAtt ChallengesTable.Arn

  avScan:
    handler: handlers/events/av-scan.handler
    events:
      - eventBridge:
          pattern:
            source:
              - dynamodb.${env:SUBMISSIONS_TABLE}
            detail-type:
              - INSERT
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:GetObject
          - s3:DeleteObject
          - s3:ListBucket
        Resource: arn:aws:s3:::${env:SUBMISSIONS_DMZ_BUCKET}/*
      - Effect: Allow
        Action:
          - s3:PutObject
          - s3:ListBucket
        Resource: arn:aws:s3:::${env:SUBMISSIONS_QUARANTINE_BUCKET}/*
      - Effect: Allow
        Action:
          - s3:PutObject
          - s3:ListBucket
        Resource: arn:aws:s3:::${env:SUBMISSIONS_BUCKET}/*

  updateScanResult:
    handler: handlers/events/update-scan-result.handler
    events:
      - eventBridge:
          pattern:
            source:
              - aws.s3
            detail-type:
              - AWS API Call via CloudTrail
            detail:
              eventSource:
                - s3.amazonaws.com
              eventName:
                - CopyObject
              requestParameters:
                bucketName:
                  - ${env:SUBMISSIONS_BUCKET}
                  - ${env:SUBMISSIONS_QUARANTINE_BUCKET}
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource: !GetAtt SubmissionsTable.Arn
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: !Sub ${SubmissionsTable.Arn}/index/FilenameIndex

  incrementSubCount:
    handler: handlers/events/increment-submissions-count.handler
    events:
      - eventBridge:
          pattern:
            source:
              - dynamodb.${env:SUBMISSIONS_TABLE}
            detail-type:
              - MODIFY
            detail:
              newImage:
                avScanPass:
                  - true
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource: !GetAtt ChallengesTable.Arn

  updateChallengeStatus:
    handler: handlers/events/update-challenge-status.handler
    events:
      - eventBridge:
          pattern:
            source:
              - dynamodb.${env:SUBMISSION_REVIEWS_TABLE}
            detail-type:
              - INSERT
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource: !GetAtt ChallengesTable.Arn
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: !Sub ${SubmissionsTable.Arn}/index/ChallengeIndex
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: !Sub ${ReviewsTable.Arn}/index/SubmissionIndex

  schedulePhases:
    handler: handlers/events/schedule-phases.handler
    events:
      - eventBridge:
          pattern:
            source:
              - dynamodb.${env:CHALLENGES_TABLE}
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
        Resource: !GetAtt ChallengesTable.Arn

  screeningPhase:
    handler: handlers/events/start-screening-phase.handler
    events:
      - eventBridge:
          pattern:
            source:
              - dynamodb.${env:CHALLENGES_TABLE}
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
        Resource: !GetAtt ChallengesTable.Arn

  reviewPhases:
    handler: handlers/events/start-review-phase.handler
    events:
      - eventBridge:
          pattern:
            source:
              - dynamodb.${env:SUBMISSIONS_TABLE}
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
        Resource: !GetAtt SubmissionsTable.Arn

        


        
